CREATE TABLE MERCADO (
    Id_Merc SERIAL PRIMARY KEY,
    Tel_Merc VARCHAR(15),
    Nome_Merc VARCHAR(100) NOT NULL,
    Hora_abertura TIME,
    Ender_merc VARCHAR(255)
);

CREATE TABLE CLIENTE (
    Id_Client SERIAL PRIMARY KEY,
    Cpf_Client VARCHAR(14) UNIQUE NOT NULL,
    Nome_Client VARCHAR(100) NOT NULL,
    Nacionalidade VARCHAR(50),
    Idade_Client INT
);

CREATE TABLE FUNCIONARIO (
    Id_Func SERIAL PRIMARY KEY,
    Nome_Func VARCHAR(100) NOT NULL,
    Cpf_Func VARCHAR(14) UNIQUE NOT NULL,
    Tel_Func VARCHAR(15),
    Idade_Func INT
);

CREATE TABLE ATENDIMENTO (
    Id_Atend SERIAL PRIMARY KEY,
    Id_Merc INT REFERENCES MERCADO(Id_Merc) ON DELETE CASCADE,
    Id_Client INT REFERENCES CLIENTE(Id_Client) ON DELETE CASCADE,
    Id_Func INT REFERENCES FUNCIONARIO(Id_Func) ON DELETE CASCADE
);

CREATE TABLE PRODUTO (
    Id_Prod SERIAL PRIMARY KEY,
    Nome_Prod VARCHAR(100) NOT NULL,
    Valor_Prod DECIMAL(10,2) NOT NULL,
    Fornecedor VARCHAR(100),
    Data_Vencimento DATE
);

CREATE TABLE COMPRA (
    Id_Compra SERIAL PRIMARY KEY,
    Id_Atend INT REFERENCES ATENDIMENTO(Id_Atend) ON DELETE CASCADE,
    Id_Prod INT REFERENCES PRODUTO(Id_Prod) ON DELETE CASCADE,
    Valor_Total DECIMAL(10,2) NOT NULL,
    Forma_Pagam VARCHAR(50) NOT NULL,
    Quant_Prod INT,
    Ender_Entrega VARCHAR(255)
);
